#
###################################
# Site wide configuration
####################################
#
title: Mukkamala Mahesh Chandra, Mathematical Optimization Group, Saarland University. Occassionally blogging about Inertial Bregman Proximal Gradient Algorithm in Non-convex Non-smooth Non-Lipschitz optimization and novel Matrix Factorization methods.
email:
description: Mathematical Optimization Thoughts, blog on Inertial Bregman Proximal Gradient Algorithm and in general on Non-convex Non-smooth Non-Lipschitz  optimization, maybe Convex optimization and Matrix Factorization.
url: # the base hostname & protocol for your site
comments: true


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Mahesh Chandra Mukkamala
  avatar: 
  job: "Phd Student, Mathematical Optimization Group, Saarland University"
  bio: ""
  email: 
  disqus-shortname: disqus_hfXAYgnWPX
  twitter: mmahesh873
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mmahesh
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: maheshchandra
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
